name: Tchalalala

on:
  schedule:
    - cron: "*/15 0-23 * * 1-6"
  push:
    branches:
      - main

env:
  FILE_NAME: hello-server

jobs:
  BuildGo:
    name: Build Go
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Go Code
      uses: actions/checkout@v2

    - name: Build ${{ env.FILE_NAME }} for ubuntu-latest
      run: go build ${{ env.FILE_NAME }}.go

    - name: Build ${{ env.FILE_NAME }} for windows-latest
      run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go

    - name: Upload artifact for linux
      uses: actions/upload-artifact@v1.0.0
      with:
        name: linux
        path: ./${{ env.FILE_NAME }}

    - name: Upload artifact for windows
      uses: actions/upload-artifact@v1.0.0
      with:
        name: windows
        path: ./${{ env.FILE_NAME}}.exe

  down-and-run-linux:
    name: Download and run Linux
    runs-on: ubuntu-latest
    needs: BuildGo
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Abajar hermano jajaja
      uses: actions/download-artifact@v1.0.0
      with:
        name: linux

    - name: Ler script run.sh
      run: source ./run.sh

  download-only-windows:
    name: Download Windows
    runs-on: windows-latest
    needs: BuildGo
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Yo soy bill gates
      uses: actions/download-artifact@v1.0.0
      with:
        name: windows
